#!/usr/bin/env python3
"""Prepare the scrolling photo strips.

  python3 tools/build_photos.py         group photos  imgs/photos/ -> data/photos.js  (home, team, research)
  python3 tools/build_photos.py city    city photos   imgs/city/   -> data/city.js    (open positions)

1. Put photos (jpg/jpeg/png) in the folder
2. Run the command above
3. Reload the site.

For every photo it writes a light, correctly-rotated copy to assets/img/hero/
(height 800 px, JPEG ~80%) and regenerates data/photos.js, the list used by the
home page. Originals are never modified. Remove a photo from imgs/photos/ and
re-run to take it off the strip.
"""
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
SET = sys.argv[1] if len(sys.argv) > 1 else "photos"
CFG = {"photos": ("photos", "hero", "photos.js", "PHOTOS"), "city": ("city", "city", "city.js", "CITY")}
if SET not in CFG:
    sys.exit("usage: build_photos.py [photos|city]")
_src, _out, _manifest, VAR = CFG[SET]
SRC = ROOT / "imgs" / _src
OUT = ROOT / "assets" / "img" / _out
MANIFEST = ROOT / "data" / _manifest
HEIGHT = 800
EXTS = {".jpg", ".jpeg", ".png"}


def main():
    files = sorted(p for p in SRC.iterdir() if p.suffix.lower() in EXTS) if SRC.is_dir() else []
    if not files:
        sys.exit(f"No photos found in {SRC}")

    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.jpg"):  # keep the folder in sync with the sources
        old.unlink()

    names = []
    for f in files:
        img = ImageOps.exif_transpose(Image.open(f)).convert("RGB")
        if img.height > HEIGHT:
            img = img.resize((round(img.width * HEIGHT / img.height), HEIGHT), Image.LANCZOS)
        name = f.stem.replace(" ", "-") + ".jpg"
        img.save(OUT / name, "JPEG", quality=80, optimize=True, progressive=True)
        names.append(name)
        print(f"  {f.name:40s} -> {name} ({img.width}x{img.height}, {(OUT / name).stat().st_size // 1024} KB)")

    items = ",\n".join(f'  "assets/img/{_out}/{n}"' for n in names)
    MANIFEST.write_text(
        "/* Generated by tools/build_photos.py – do not edit by hand. */\n"
        f"window.{VAR} = [\n{items}\n];\n"
    )
    print(f"\n{len(names)} photos -> {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
